# Generated by Django 5.2.7 on 2025-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuário Cadastrado',
                'verbose_name_plural': 'Usuários Cadastrados',
            },
        ),
    ]
