# Generated by Django 5.2.8 on 2025-11-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocadastro',
            name='termos_aceitos',
            field=models.BooleanField(default=False),
        ),
    ]
